n=5;
for i = 1:n
    for j = 1:n
        testvals = combvec(i-1:i+1,j-1:j+1);
        testvals(:,all([ ...
            all(testvals<=n); ...
            all(testvals>=1); ...
            any(testvals~=[i;j])...
            ]))
%         testvals = testvals(testvals>=1)
    end
end
